GET http://localhost:3000/ HTTP/1.1

###
GET http://localhost:3000/article HTTP/1.1

###

POST http://localhost:3000/article
Content-Type: application/json

{
  "title": "Getting Started with NestJS",
  "content": "This is an introduction to NestJS framework..."
}

###
POST http://localhost:3000/article
Content-Type: application/json

{
  "title": "Getting Started with Python for Web App",
  "content": "This is an intermediate lectures to Django framework..."
}

###
POST http://localhost:3000/article
Content-Type: application/json

{
  "title": "Advanced Level Design Pattern ",
  "content": "Advanced level lessons on Software Design Patterns",
  "author": "Me"
}

###
GET http://localhost:3000/article/1 HTTP/1.1


###
PATCH http://localhost:3000/article/3 HTTP/1.1
Content-Type: application/json

{
  "title": "How to build a house 1",
  "content": "DIY on how to build your own very humble house. Get started by ...",
  "author": "Me and you"
}

###
DELETE http://localhost:3000/article/2 HTTP/1.1

